services:
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kunatalk
      - MONGO_INITDB_ROOT_PASSWORD=kunatalk
      - MONGO_INITDB_DATABASE=kunaTalk
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27017:27017'
    command: ['mongod', '--config', '/etc/mongo/mongod.conf']
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://kunatalk:kunatalk@mongo:27017
    ports:
      - '8000:8000'
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
